[project]
name = "mcp-coinmarketcap"
version = "0.1.0"
dependencies = [
    "fastmcp",
    "requests",
    "pydantic",
    "pydantic-settings",
    "python-dotenv"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

